use crate::types::{Address, Bits, Register};

#[derive(Copy, Clone, Debug)]
pub enum Instruction {
    Nop,

    Add(Register, Register, Register),
    AddImmediate(Register, Register, Bits),
    Sub(Register, Register, Register),
    SubImmediate(Register, Register, Bits),
    Mul(Register, Register, Register),
    MulImmediate(Register, Register, Bits),
    DivMod(Register, Register, Register, Register),
    DivModImmediate(Register, Register, Register, Bits),
    Div(Register, Register, Register),
    DivImmediate(Register, Register, Bits),
    Mod(Register, Register, Register),
    ModImmediate(Register, Register, Bits),

    Not(Register, Register),
    NotImmediate(Register, Bits),
    GreaterThan(Register, Register, Register),
    GreaterThanImmediate(Register, Register, Bits),
    LessThan(Register, Register, Register),
    LessThanImmediate(Register, Register, Bits),
    GreaterThanOrEqual(Register, Register, Register),
    GreaterThanOrEqualImmediate(Register, Register, Bits),
    LessThanOrEqual(Register, Register, Register),
    LessThanOrEqualImmediate(Register, Register, Bits),
    Equal(Register, Register, Register),
    EqualImmediate(Register, Register, Bits),
    NotEqual(Register, Register, Register),
    NotEqualImmediate(Register, Register, Bits),

    FloatAdd(Register, Register, Register),
    FloatAddImmediate(Register, Register, Bits),
    FloatSub(Register, Register, Register),
    FloatSubImmediate(Register, Register, Bits),
    FloatMul(Register, Register, Register),
    FloatMulImmediate(Register, Register, Bits),
    FloatDivMod(Register, Register, Register, Register),
    FloatDivModImmediate(Register, Register, Register, Bits),
    FloatDiv(Register, Register, Register),
    FloatDivImmediate(Register, Register, Bits),
    FloatMod(Register, Register, Register),
    FloatModImmediate(Register, Register, Bits),

    FloatGreaterThan(Register, Register, Register),
    FloatGreaterThanImmediate(Register, Register, Bits),
    FloatLessThan(Register, Register, Register),
    FloatLessThanImmediate(Register, Register, Bits),
    FloatGreaterThanOrEqual(Register, Register, Register),
    FloatGreaterThanOrEqualImmediate(Register, Register, Bits),
    FloatLessThanOrEqual(Register, Register, Register),
    FloatLessThanOrEqualImmediate(Register, Register, Bits),
    FloatEqual(Register, Register, Register),
    FloatEqualImmediate(Register, Register, Bits),
    FloatNotEqual(Register, Register, Register),
    FloatNotEqualImmediate(Register, Register, Bits),
    FloatNegate(Register, Register),
    FloatNegateImmediate(Register, Bits),

    SignedAdd(Register, Register, Register),
    SignedAddImmediate(Register, Register, Bits),
    SignedSub(Register, Register, Register),
    SignedSubImmediate(Register, Register, Bits),
    SignedMul(Register, Register, Register),
    SignedMulImmediate(Register, Register, Bits),
    SignedDivMod(Register, Register, Register, Register),
    SignedDivModImmediate(Register, Register, Register, Bits),
    SignedDiv(Register, Register, Register),
    SignedDivImmediate(Register, Register, Bits),
    SignedMod(Register, Register, Register),
    SignedModImmediate(Register, Register, Bits),

    SignedGreaterThan(Register, Register, Register),
    SignedGreaterThanImmediate(Register, Register, Bits),
    SignedLessThan(Register, Register, Register),
    SignedLessThanImmediate(Register, Register, Bits),
    SignedGreaterThanOrEqual(Register, Register, Register),
    SignedGreaterThanOrEqualImmediate(Register, Register, Bits),
    SignedLessThanOrEqual(Register, Register, Register),
    SignedLessThanOrEqualImmediate(Register, Register, Bits),
    SignedEqual(Register, Register, Register),
    SignedEqualImmediate(Register, Register, Bits),
    SignedNotEqual(Register, Register, Register),
    SignedNotEqualImmediate(Register, Register, Bits),
    SignedNegate(Register, Register),
    SignedNegateImmediate(Register, Bits),

    And(Register, Register, Register),
    AndImmediate(Register, Register, Bits),
    Or(Register, Register, Register),
    OrImmediate(Register, Register, Bits),
    Xor(Register, Register, Register),
    XorImmediate(Register, Register, Bits),
    LeftShift(Register, Register, Register),
    LeftShiftImmediate(Register, Register, Bits),
    RightShift(Register, Register, Register),
    RightShiftImmediate(Register, Register, Bits),

    Jump(Register),
    JumpImmediate(Address),
    JumpIfNotZero(Register, Register),
    JumpIfNotZeroImmediate(Register, Address),

    Move(Register, Register),
    MoveImmediate(Register, Bits),

    Push(Register),
    PushImmediate(Bits),
    Pop(Register),

    Store(Address, Register),
    StoreImmediate(Address, Bits),
    Load(Register, Register),
    LoadImmediate(Register, Address),

    Call(Address),
    Return,
}